///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String boldHome = 'assets/images/vuesax/bold/home.svg';
  static const String boldProducts = 'assets/images/vuesax/bold/products.svg';
  static const String boldShoppingCart = 'assets/images/vuesax/bold/shopping-cart.svg';
  static const String boldUser = 'assets/images/vuesax/bold/user.svg';
  static const String fontsCairoBold = 'assets/fonts/Cairo-Bold.ttf';
  static const String fontsCairoMedium = 'assets/fonts/Cairo-Medium.ttf';
  static const String fontsCairoRegular = 'assets/fonts/Cairo-Regular.ttf';
  static const String fontsCairoSemiBold = 'assets/fonts/Cairo-SemiBold.ttf';
  static const String imagesAppIcon = 'assets/images/app_icon.png';
  static const String imagesApplIcon = 'assets/images/appl_icon.svg';
  static const String imagesCheck = 'assets/images/Check.svg';
  static const String imagesEdit = 'assets/images/edit.svg';
  static const String imagesFacebookIcon = 'assets/images/facebook_icon.svg';
  static const String imagesFeaturedItemBackground = 'assets/images/featured_item_background.svg';
  static const String imagesFilter = 'assets/images/filter.svg';
  static const String imagesFilter2 = 'assets/images/filter2.svg';
  static const String imagesGoogleIcon = 'assets/images/google_icon.svg';
  static const String imagesLocation = 'assets/images/location.svg';
  static const String imagesLogo = 'assets/images/logo.svg';
  static const String imagesNotification = 'assets/images/notification.svg';
  static const String imagesPageViewItem1BackgroundImage = 'assets/images/page_view_item1_background_image.svg';
  static const String imagesPageViewItem1Image = 'assets/images/page_view_item1_image.svg';
  static const String imagesPageViewItem2BackgroundImage = 'assets/images/page_view_item2_background_image.svg';
  static const String imagesPageViewItem2Image = 'assets/images/page_view_item2_image.svg';
  static const String imagesPlant = 'assets/images/plant.svg';
  static const String imagesProfileImage = 'assets/images/profile_image.png';
  static const String imagesSearchIcon = 'assets/images/search_icon.svg';
  static const String imagesSplashBottom = 'assets/images/splash_bottom.svg';
  static const String imagesTrash = 'assets/images/trash.svg';
  static const String imagesVector = 'assets/images/Vector.svg';
  static const String imagesWatermelonTest = 'assets/images/watermelon_test.png';
  static const String outlineHome = 'assets/images/vuesax/outline/home.svg';
  static const String outlineProducts = 'assets/images/vuesax/outline/products.svg';
  static const String outlineShoppingCart = 'assets/images/vuesax/outline/shopping-cart.svg';
  static const String outlineUser = 'assets/images/vuesax/outline/user.svg';
  static const String utilsImages = 'lib/core/utils/images.dart';
  static const String imageOffers= "assets/images/editeoffers1.png";
  static const String imageOffers2= "assets/images/editeoffers.png";
  static const String banana="assets/images/Bitmap.png";
  static const String mango= "assets/images/mango-transparent-background-free-png 2.png";
  static const String avocado= "assets/images/Avocado-PNG-Clipart 1.png";
  static const String pineapple= "assets/images/pineapple-fruit-transparent-background-free-png 1.png";
  static const String strawberry= "assets/images/strawberry.png";
  static const String oval= "assets/images/ovall.png";
}
