// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdk9O9QgiwTIhqZlsmn5udsswgY5THTHk',
    appId: '1:148756726715:web:3bbdd4f4d8784f43413a9e',
    messagingSenderId: '148756726715',
    projectId: 'foodapp-15ef0',
    authDomain: 'foodapp-15ef0.firebaseapp.com',
    storageBucket: 'foodapp-15ef0.firebasestorage.app',
    measurementId: 'G-E2819FKVXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrRk9cS3b895OMyOI4N82gvzHDbU6fY5w',
    appId: '1:148756726715:android:d915b16eb1a6eb53413a9e',
    messagingSenderId: '148756726715',
    projectId: 'foodapp-15ef0',
    storageBucket: 'foodapp-15ef0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYEueDBHX7XC2Dq2KaG7KjX6lVFqHjQC8',
    appId: '1:148756726715:ios:c5f408f0b9c200bf413a9e',
    messagingSenderId: '148756726715',
    projectId: 'foodapp-15ef0',
    storageBucket: 'foodapp-15ef0.firebasestorage.app',
    androidClientId: '148756726715-50sov4uar0j3ri8rj2f2c0gts0ovbgha.apps.googleusercontent.com',
    iosClientId: '148756726715-22gj8pp5j79jak2m406e3s9in6ksbcbe.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashboardECommerceFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYEueDBHX7XC2Dq2KaG7KjX6lVFqHjQC8',
    appId: '1:148756726715:ios:c5f408f0b9c200bf413a9e',
    messagingSenderId: '148756726715',
    projectId: 'foodapp-15ef0',
    storageBucket: 'foodapp-15ef0.firebasestorage.app',
    androidClientId: '148756726715-50sov4uar0j3ri8rj2f2c0gts0ovbgha.apps.googleusercontent.com',
    iosClientId: '148756726715-22gj8pp5j79jak2m406e3s9in6ksbcbe.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashboardECommerceFood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdk9O9QgiwTIhqZlsmn5udsswgY5THTHk',
    appId: '1:148756726715:web:58eb8ffca3f4f800413a9e',
    messagingSenderId: '148756726715',
    projectId: 'foodapp-15ef0',
    authDomain: 'foodapp-15ef0.firebaseapp.com',
    storageBucket: 'foodapp-15ef0.firebasestorage.app',
    measurementId: 'G-YF3NGRN0Q3',
  );
}
